### ISSUE TITLE
Ubuntu Build error

### ISSUE THREAD

**Issue by toastedBread1** [sjoerd108/jimp-native#3]
Hey, I've got this error (Ubuntu 16.04)
Node Version: v16.14.0
NPM Version: v9.3.0
Node-Gyp Version: v9.3.1

npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../cppsrc/js-wrappers/../modules/blit.hpp:2:0,
npm ERR!                  from ../cppsrc/js-wrappers/wrapBlit.cpp:2:
npm ERR! ../cppsrc/js-wrappers/../modules/../util/image.hpp:4:20: fatal error: optional: No such file or directory
npm ERR! compilation terminated.
npm ERR! make: *** [Release/obj.target/jimp-native/cppsrc/js-wrappers/wrapBlit.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by sjoerdthedev** [comment]
Hm, that's a bit strange. I'll spin up a Ubuntu 16.04 VM and look into it. Thanks for reporting the issue

**Comment by toastedBread1** [comment]
any update on this?

**Comment by sjoerdthedev** [comment]
I had a look at it in a 16.04 setup and I'm able to reproduce it. I can't pinpoint why this happens though. It's not an issue if I install the same version of node on more recent versions of Ubuntu. I'm still looking into it.

**Comment by sjoerdthedev** [comment]
After some more digging, I've found the reason why this happens. Ubuntu 16.04 ships with a pretty old version of g++. jimp-native needs C++17 support to work properly. The error you're seeing is because it's unable to load `optional` from the standard library.

I'm afraid you're going to have to upgrade your version of Ubuntu or find a way to get a more recent version of g++ (from what I can find you'll need at least version 7.1) on your machine to get the build to work. You may have some luck with a PPA. Note that Ubuntu 16.04 is at end of life so if you have any choice in the matter then upgrading is probably the best idea here.
